version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: gasgen_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  bot:
    build: .
    container_name: gasgen_bot
    command: >-
      watchmedo auto-restart
      --directory=/app
      --pattern="*.py"
      --recursive
      --signal=SIGINT --
      python telegram_bot/main.py
    volumes:
      - ./:/app
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      TZ: Europe/Kyiv
    restart: on-failure

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gasgen_celery
    command: >-
      watchmedo auto-restart
      --directory=/app
      --pattern="*.py"
      --recursive
      --signal=SIGINT --
      celery -A celery_tasks worker -n gbot -l INFO -Q gasgen
    env_file:
      - .env
    environment:
      TZ: Europe/Kyiv
    volumes:
      - ./:/app
    depends_on:
      - bot
      - redis
    restart: on-failure
